name: Update HLA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  refresh:
    name: Refresh HLA sequences
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '3.8'
        - name: Refresh HLA sequences
          id: check_files
          run: |
            make refresh-hla-seqs
            FNAME=$(git diff --name-only ontology/chain-sequence.tsv)
            if [[ $FNAME == ontology/chain-sequence.tsv ]]; then
              echo "::set-output name=has_change::true"
            else
              echo "::set-output name=has_change::false"
            fi
        - name: Create commit
          id: create_commit
          if: steps.check_files.outputs.has_change == 'true'
          run: |
            git config user.name 'github-actions'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git commit -am "$(date '+%Y-%m-%d') HLA refresh"
            echo "::set-output name=date::$(date +'%Y-%m-%d')"
        - name: Create pull request
          if: steps.check_files.outputs.has_change == 'true'
          uses: peter-evans/create-pull-request@v3
          with:
            title: ${{ steps.create_commit.outputs.date }} HLA Sequence Update
            branch: ${{ steps.create_commit.outputs.date }}-hla-update
            reviewers: |
              jamesaoverton
              rvita
            body: |
              Refresh HLA sequences (auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request))
